# Generated by Django 3.1.2 on 2020-10-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='details/images/')),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('relationshipID', models.IntegerField()),
                ('parentID', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBY', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
            ],
        ),
    ]
