# Generated by Django 3.1.2 on 2020-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20201022_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='invitationID',
            field=models.IntegerField(default=' '),
        ),
        migrations.AddField(
            model_name='person',
            name='relationtoreferred',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
