# Generated by Django 3.1.2 on 2020-10-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20201023_1440'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name', 'sur_name', 'city')},
        ),
    ]
